Revisions in Server to avoid application fail on Server errors
cutelyst/cutelyst pull request #308
Opened 2021-04-09 13:43 UTC by MikePooh

Most of qFatals and exit()s has been replaced by handlers which emits errorOccured signal. This behavior will prevent qApplication fail on Server errors.

2021-04-09 14:06 UTC, dantti requested changes
Mostly ok, thanks!

2021-04-09 14:06 UTC, dantti commented on server/server.cpp
> +//#endif
If this change is going to happen this comments can go

2021-04-09 14:06 UTC, dantti commented on server/server.cpp
> +    if (!d->userEventLoop) { //launchs Event loop only in case standalone app, not embedded
This is missing qEnvironmentVariableIsSet("CUTELYST_QT_EVENT_LOOP") as cutelystd might be used with default event loop.
The comment is also a bid misleading, as I might embedded it to get better at LTO and still want EPool.

2021-04-09 14:07 UTC, dantti commented
while you are at it #213 is related and might hit you :)

2021-04-09 14:29 UTC, MikePooh commented on server/server.cpp
> +    std::cout << "Mikes Version of Cutelyst" << std::endl;
Haha, indeed. I just placed it to be sure I am using forked version of library, not original on tests :)

2021-04-10 14:24 UTC, dantti commented on server/main.cpp
> +        qFatal("Server terminated due to error %s", error.toStdString().c_str());});
better use qPrintable

2021-04-10 15:49 UTC, merged