Fixed incorrect saving of the file name when loading, named in Cyrillic
cutelyst/cutelyst pull request #336
Opened 2022-02-11 20:06 UTC by sanekt197

When loading a file with a Russian name on a disk, the name is saved with incorrect characters. Solved by unicode header.
For example, a file with the name "Привет мир.JPG" was saved to a disk with the name "ÐÑÐ¸Ð²ÐµÑ Ð¼Ð¸Ñ.JPG".

In general, globally there are fears of incorrect behavior with Russian characters, for example, when submitting forms or authorization, it will be necessary to check everything ...

2022-02-11 20:17 UTC, dantti commented
I wonder if they shouldn't be URL encoded

2022-02-11 20:24 UTC, sanekt197 commented
I understand it happens after. 
And it seems like the filename parameter already contains this "garbage" in the header itself.
And it's saved to disk like this:
![Screenshot 2022-02-11 at 23 23 42](https://user-images.githubusercontent.com/29947036/153664873-954af082-a215-4bbe-86c0-c240f50294ba.png)

2022-02-11 20:29 UTC, dantti commented
Yes, I can reproduce the issue. But due https://github.com/postmanlabs/postman-app-support/issues/5912 I'm confused on what's the proper way to do it. will dump to see what chrome & friends send

2022-02-11 20:41 UTC, dantti requested changes

2022-02-11 20:41 UTC, dantti commented on Cutelyst/multipartformdataparser.cpp
> +                    headers.setHeader(QString::fromUtf8(headerLine.left(dotdot)),
This is the header name so no need to call the slow fromUtf8

2022-02-15 00:22 UTC, dantti commented
Fixed in #336

2022-02-15 00:22 UTC, closed without merging